spring.application.name=Portfolio

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=postgres
spring.datasource.password=hex69
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

jwt.secret=mi_clave_super_secreta_123456789123456789

app.frontend.url=http://localhost:3000